import type { Digest } from "./summarize";

export const MOCK_DIGEST: Digest = {
  generatedAt: new Date().toISOString(),
  articles: [
    // Physical AI - Deal Signal
    {
      title: "Physical Intelligence Raises $400M Series B at $2.7B Valuation",
      url: "https://example.com/pi-funding",
      source: "TechCrunch",
      publishedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      ogImage: "https://example.com/pi-logo.jpg",
      beat: "Physical AI",
      category: "Funding",
      companyTags: ["Physical Intelligence"],
      summary: "Physical Intelligence, the humanoid AI robotics company, has closed a Series B funding round. The funding will accelerate development of their general-purpose mobile manipulation platform.",
      bdRelevance: "Critical partnership signal: PI is positioning as the platform layer for embodied AI. Potential collaboration angle on enterprise deployment.",
      relevanceScore: 10,
      impactScore: 9,
      impactReason: "Validates commercial viability of embodied AI; positions PI as infrastructure play",
      dealSignal: true,
      dealSignalType: "funding_round",
    },
    // Physical AI - Regular
    {
      title: "Tesla Optimus Now Performing Manufacturing Tasks in Pilot Program",
      url: "https://example.com/tesla-optimus",
      source: "RoboHub",
      publishedAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
      ogImage: null,
      beat: "Physical AI",
      category: "Product",
      companyTags: ["Tesla"],
      summary: "Tesla announced that Optimus humanoid robots are now actively performing manufacturing tasks in Gigafactory pilot programs. Early deployments focus on repetitive assembly work.",
      bdRelevance: "Tesla Optimus represents the fastest path to commercial humanoid deployment. Monitor for partnership opportunities as manufacturing scale ramps.",
      relevanceScore: 8,
      impactScore: 7,
      impactReason: "Demonstrates commercial viability of humanoid robots in controlled environments",
      dealSignal: false,
    },
    // AI Infrastructure - Deal Signal
    {
      title: "Modal Announces Enterprise Deployment Program for AI Workflows",
      url: "https://example.com/modal-enterprise",
      source: "Modal Blog",
      publishedAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
      ogImage: "https://example.com/modal-logo.jpg",
      beat: "AI Infrastructure",
      category: "Product",
      companyTags: ["Modal"],
      summary: "Modal, the serverless compute platform for AI, launched an enterprise deployment program targeting Fortune 500 companies. Program includes dedicated infrastructure and support.",
      bdRelevance: "Modal's enterprise program is a partnership play. May create co-go-to-market opportunities for AI companies building on their infrastructure.",
      relevanceScore: 9,
      impactScore: 6,
      impactReason: "Enterprise focus signals infrastructure maturation; creates partnership ecosystem",
      dealSignal: true,
      dealSignalType: "product_launch",
    },
    // AI Infrastructure - Regular
    {
      title: "Pinecone Releases Vector Database Optimization for Real-time Inference",
      url: "https://example.com/pinecone-optimization",
      source: "VectorDB News",
      publishedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
      ogImage: null,
      beat: "AI Infrastructure",
      category: "Product",
      companyTags: ["Pinecone"],
      summary: "Pinecone released new optimization techniques for vector database queries, reducing latency by 40% in production environments. Available for all enterprise customers.",
      bdRelevance: "Performance improvement in vector search enables new use cases for retrieval-augmented generation systems. Technical differentiation for AI product builders.",
      relevanceScore: 7,
      impactScore: 6,
      impactReason: "Incremental improvement in a foundational technology; enables better real-time experiences",
      dealSignal: false,
    },
    // AI Labs - Deal Signal
    {
      title: "Anthropic and Google Announce Strategic Partnership on AI Safety Research",
      url: "https://example.com/anthropic-google",
      source: "Anthropic Blog",
      publishedAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      ogImage: "https://example.com/anthropic-logo.jpg",
      beat: "AI Labs",
      category: "Partnerships",
      companyTags: ["Anthropic", "Google"],
      summary: "Anthropic and Google announced a joint research partnership focused on AI safety and interpretability. The collaboration will combine Anthropic's research with Google's infrastructure.",
      bdRelevance: "Major research partnership signals competitive positioning. Companies building on Claude may want to understand safety research direction and standards.",
      relevanceScore: 8,
      impactScore: 8,
      impactReason: "Major AI labs converging on safety research; may establish new industry standards",
      dealSignal: true,
      dealSignalType: "partnership_announced",
    },
    // AI Labs - Regular
    {
      title: "OpenAI Releases GPT-4.5 with Improved Reasoning Capabilities",
      url: "https://example.com/openai-gpt45",
      source: "OpenAI Blog",
      publishedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
      ogImage: null,
      beat: "AI Labs",
      category: "AI/Models",
      companyTags: ["OpenAI"],
      summary: "OpenAI released GPT-4.5 with enhanced multi-step reasoning and improved code generation. The model shows 15% improvement in complex reasoning benchmarks.",
      bdRelevance: "Model capability progression affects competitive landscape for AI products. Assess impact on feature differentiation and performance requirements.",
      relevanceScore: 7,
      impactScore: 7,
      impactReason: "Incremental capability improvement in foundational model; raises bar for AI applications",
      dealSignal: false,
    },
    // Vertical AI - Deal Signal
    {
      title: "Harvey AI Lands Goldman Sachs as Major Enterprise Customer",
      url: "https://example.com/harvey-goldman",
      source: "VentureBeat",
      publishedAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
      ogImage: "https://example.com/harvey-logo.jpg",
      beat: "Vertical AI",
      category: "Partnerships",
      companyTags: ["Harvey"],
      summary: "Harvey AI, the legal AI platform, announced Goldman Sachs as a major enterprise customer. Goldman will deploy Harvey across legal and compliance functions.",
      bdRelevance: "Tier-1 financial services adoption validates enterprise AI deployment model. Watch for Harvey's potential integration partnerships and ecosystem plays.",
      relevanceScore: 9,
      impactScore: 8,
      impactReason: "Validates enterprise AI adoption in highly regulated industries; opens market opportunities",
      dealSignal: true,
      dealSignalType: "customer_win",
    },
    // Vertical AI - Regular
    {
      title: "Rogo Expands Platform to Support Additional Enterprise Workflows",
      url: "https://example.com/rogo-expansion",
      source: "Rogo Blog",
      publishedAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
      ogImage: null,
      beat: "Vertical AI",
      category: "Product",
      companyTags: ["Rogo"],
      summary: "Rogo, the enterprise workflow automation platform, expanded to support supply chain management and procurement workflows. Integration with major ERP systems now available.",
      bdRelevance: "Supply chain AI is emerging as a key enterprise need. Rogo's expansion into this space signals market development and potential partnership opportunities.",
      relevanceScore: 6,
      impactScore: 5,
      impactReason: "Addresses emerging enterprise need in supply chain optimization; expands addressable market",
      dealSignal: false,
    },
  ],
};
