import type { Digest } from "./summarize";

const T = (hoursAgo: number) => new Date(Date.now() - hoursAgo * 60 * 60 * 1000).toISOString();

export const MOCK_DIGEST: Digest = {
  generatedAt: new Date().toISOString(),
  synthesis: {
    thesis: "Physical Intelligence's $400M raise signals that embodied AI is crossing from research into commercial infrastructure — the same dynamic that preceded the cloud build-out. BD teams should be mapping integration and partnership opportunities now, before vendor lock-in sets.",
    emailSubject: "Physical Intelligence raises $400M — embodied AI inflects",
  },
  articles: [
    // ========== PHYSICAL AI (10 articles) ==========
    // dealSignal articles first, sorted newest → oldest within group
    {
      title: "Physical Intelligence Raises $400M Series B at $2.7B Valuation",
      url: "https://example.com/pi-funding",
      source: "TechCrunch",
      publishedAt: T(0.5),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/physicalintelligence.com",
      beat: "Physical AI",
      category: "Funding",
      companyTags: ["Physical Intelligence"],
      summary: "Physical Intelligence closed a $400M Series B round at a $2.7B valuation. Funding will accelerate development of their general-purpose mobile manipulation platform.",
      bdRelevance: "PI is positioning as the platform layer for embodied AI. Strong partnership and enterprise deployment angle.",
      relevanceScore: 10,
      impactScore: 9,
      impactReason: "Validates commercial viability of embodied AI; positions PI as infrastructure play",
      dealSignal: true,
      dealSignalType: "funding_round",
      storyId: "mock-story-1",
    },
    {
      title: "Figure AI Completes Humanoid Robot Deployment at BMW Manufacturing",
      url: "https://example.com/figure-bmw",
      source: "VentureBeat",
      publishedAt: T(2),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/figure.ai",
      beat: "Physical AI",
      category: "Partnerships",
      companyTags: ["Figure AI"],
      summary: "Figure AI announced successful deployment of its Figure 01 humanoid robots at BMW manufacturing facilities for end-of-line assembly and quality checks.",
      bdRelevance: "Tier-1 automotive partnership validates enterprise readiness for embodied AI. Gateway to supply chain opportunities.",
      relevanceScore: 9,
      impactScore: 9,
      impactReason: "Fortune 500 manufacturing partnership confirms commercial deployment viability",
      dealSignal: true,
      dealSignalType: "customer_win",
      storyId: "mock-story-2",
    },
    {
      title: "1X Technologies Secures $100M Investment for Humanoid Robotics",
      url: "https://example.com/1x-funding",
      source: "TechCrunch",
      publishedAt: T(3),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/1xtechnologies.com",
      beat: "Physical AI",
      category: "Funding",
      companyTags: ["1X Technologies"],
      summary: "1X Technologies raised $100M to accelerate development of its bipedal humanoid robot. Round led by Obvious Ventures and Samsung Next.",
      bdRelevance: "Alternative humanoid architecture gaining institutional backing. Diversification in embodied AI approaches.",
      relevanceScore: 8,
      impactScore: 8,
      impactReason: "Multiple humanoid platforms emerging; market validation for physical AI category",
      dealSignal: true,
      dealSignalType: "funding_round",
      storyId: "mock-story-3",
    },
    // non-dealSignal articles, sorted newest → oldest
    {
      title: "Tesla Optimus Now Performing Manufacturing Tasks in Pilot Program",
      url: "https://example.com/tesla-optimus",
      source: "RoboHub",
      publishedAt: T(4),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/tesla.com",
      beat: "Physical AI",
      category: "Product",
      companyTags: ["Tesla"],
      summary: "Tesla announced that Optimus humanoid robots are now actively performing manufacturing tasks in Gigafactory pilot programs. Early deployments focus on repetitive assembly work.",
      bdRelevance: "Tesla Optimus represents the fastest path to commercial humanoid deployment. Monitor for partnership opportunities as manufacturing scale ramps.",
      relevanceScore: 8,
      impactScore: 7,
      impactReason: "Demonstrates commercial viability of humanoid robots in controlled environments",
      dealSignal: false,
      storyId: "mock-story-4",
    },
    {
      title: "Boston Dynamics Announces Commercial Availability of Atlas Humanoid",
      url: "https://example.com/bd-atlas",
      source: "Boston Dynamics Blog",
      publishedAt: T(5),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/bostondynamics.com",
      beat: "Physical AI",
      category: "Product",
      companyTags: ["Boston Dynamics"],
      summary: "Boston Dynamics opened pre-orders for its Atlas humanoid robot with first commercial units shipping in Q4 2025. Pricing starts at $150,000 per unit.",
      bdRelevance: "Legacy robotics leader entering commercial humanoid market. Watch for enterprise integrator partnerships.",
      relevanceScore: 7,
      impactScore: 8,
      impactReason: "Established robotics company legitimizes humanoid market; brings manufacturing expertise",
      dealSignal: false,
      storyId: "mock-story-5",
    },
    {
      title: "Apptronik Secures $23M Series A for Industrial Humanoid Robots",
      url: "https://example.com/apptronik-funding",
      source: "Crunchbase",
      publishedAt: T(6),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/apptronik.com",
      beat: "Physical AI",
      category: "Funding",
      companyTags: ["Apptronik"],
      summary: "Apptronik closed a $23M Series A led by Intel Capital to develop bi-manual humanoid robots for manufacturing and logistics.",
      bdRelevance: "Series A validates investor confidence in industrial humanoid applications. Existing customer relationships signal product-market fit.",
      relevanceScore: 7,
      impactScore: 6,
      impactReason: "Real customer deployments with established brands validates industrial robotics segment",
      dealSignal: false,
      storyId: "mock-story-6",
    },
    {
      title: "Unitree Releases G1 Humanoid Robot with Advanced AI Perception",
      url: "https://example.com/unitree-g1",
      source: "TechCrunch China",
      publishedAt: T(7),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/unitree.com",
      beat: "Physical AI",
      category: "Product",
      companyTags: ["Unitree"],
      summary: "Unitree released the G1 humanoid robot with advanced visual reasoning and multi-modal perception. Priced at $150,000 with enterprise support.",
      bdRelevance: "International competition in humanoid robotics market emerging. Supply chain diversification opportunity.",
      relevanceScore: 6,
      impactScore: 6,
      impactReason: "Global humanoid robotics market consolidating; multiple viable platforms emerging",
      dealSignal: false,
      storyId: "mock-story-7",
    },
    {
      title: "Sanctuary AI Demonstrates Humanoid Robot Performing Complex Assembly Tasks",
      url: "https://example.com/sanctuary-demo",
      source: "RoboHub",
      publishedAt: T(8),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/sanctuaryai.com",
      beat: "Physical AI",
      category: "Product",
      companyTags: ["Sanctuary AI"],
      summary: "Sanctuary AI published videos demonstrating its humanoid robot performing complex electronics assembly requiring dexterity and spatial reasoning.",
      bdRelevance: "Technical progress in dexterous manipulation enables new manufacturing use cases. Watch for enterprise pilots.",
      relevanceScore: 6,
      impactScore: 6,
      impactReason: "Progress on complex manipulation tasks expands addressable use cases for humanoids",
      dealSignal: false,
      storyId: "mock-story-8",
    },
    {
      title: "Covariant Receives $20M Investment for AI-Powered Robotic Automation",
      url: "https://example.com/covariant-funding",
      source: "VentureBeat",
      publishedAt: T(9),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/covariant.ai",
      beat: "Physical AI",
      category: "Funding",
      companyTags: ["Covariant"],
      summary: "Covariant raised $20M to expand its computer vision and learning platform for logistics and manufacturing robotic arms.",
      bdRelevance: "Alternative approach to embodied AI through vision-driven manipulation. Complementary to bipedal humanoids.",
      relevanceScore: 6,
      impactScore: 5,
      impactReason: "Focused AI approach for specific manipulation tasks; validation of vision-driven robotics",
      dealSignal: false,
      storyId: "mock-story-9",
    },
    {
      title: "Agility Robotics Partners with DHL for Mobile Manipulation Pilots",
      url: "https://example.com/agility-dhl",
      source: "Logistics Today",
      publishedAt: T(10),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/agilityrobotics.com",
      beat: "Physical AI",
      category: "Partnerships",
      companyTags: ["Agility Robotics"],
      summary: "Agility Robotics announced a partnership with DHL to pilot Digit robots in logistics and warehouse environments for package handling and box placement.",
      bdRelevance: "Global logistics leader adopting mobile manipulation robots. Watch for supply chain modernization trends.",
      relevanceScore: 7,
      impactScore: 6,
      impactReason: "Major logistics company validation; opens supply chain automation market segment",
      dealSignal: false,
      storyId: "mock-story-10",
    },

    // ========== AI INFRASTRUCTURE (10 articles) ==========
    // dealSignal articles first, sorted newest → oldest
    {
      title: "Modal Announces Enterprise Deployment Program for AI Workflows",
      url: "https://example.com/modal-enterprise",
      source: "Modal Blog",
      publishedAt: T(1),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/modal.com",
      beat: "AI Infrastructure",
      category: "Product",
      companyTags: ["Modal"],
      summary: "Modal launched an enterprise deployment program targeting Fortune 500 companies with dedicated infrastructure and support.",
      bdRelevance: "Modal's enterprise program creates co-go-to-market opportunities for AI companies building on their infrastructure.",
      relevanceScore: 9,
      impactScore: 6,
      impactReason: "Enterprise focus signals infrastructure maturation; creates partnership ecosystem",
      dealSignal: true,
      dealSignalType: "product_launch",
      storyId: "mock-story-11",
    },
    {
      title: "Replicate Launches Model API with Fine-tuning Support for Enterprise",
      url: "https://example.com/replicate-finetuning",
      source: "Replicate Blog",
      publishedAt: T(2),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/replicate.com",
      beat: "AI Infrastructure",
      category: "Product",
      companyTags: ["Replicate"],
      summary: "Replicate released fine-tuning capabilities allowing enterprises to customize open-source models on their own data with dedicated GPU infrastructure.",
      bdRelevance: "Fine-tuning infrastructure enables customization for enterprise use cases. Potential integration opportunities.",
      relevanceScore: 8,
      impactScore: 7,
      impactReason: "Fine-tuning infrastructure lowers barrier for enterprise model customization",
      dealSignal: true,
      dealSignalType: "product_launch",
      storyId: "mock-story-12",
    },
    {
      title: "Together AI Secures $105M in Series B Funding for AI Infrastructure",
      url: "https://example.com/together-seriesb",
      source: "TechCrunch",
      publishedAt: T(3),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/together.ai",
      beat: "AI Infrastructure",
      category: "Funding",
      companyTags: ["Together AI"],
      summary: "Together AI raised $105M in Series B funding to expand its distributed cloud infrastructure for training and deploying large language models at scale.",
      bdRelevance: "Well-funded competitor in distributed AI infrastructure space. Watch for ecosystem partnerships and integrations.",
      relevanceScore: 8,
      impactScore: 7,
      impactReason: "Major funding validates commercial viability of distributed AI infrastructure",
      dealSignal: true,
      dealSignalType: "funding_round",
      storyId: "mock-story-13",
    },
    // non-dealSignal articles, sorted newest → oldest
    {
      title: "LangChain Launches Managed Vector Store and Deployment Platform",
      url: "https://example.com/langchain-managed",
      source: "LangChain Blog",
      publishedAt: T(4),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/langchain.com",
      beat: "AI Infrastructure",
      category: "Product",
      companyTags: ["LangChain"],
      summary: "LangChain released a managed vector store service and deployment platform to simplify RAG application deployment at scale.",
      bdRelevance: "Managed services lower operational overhead for LangChain-based applications. Integration opportunity.",
      relevanceScore: 7,
      impactScore: 6,
      impactReason: "Managed service offering expands LangChain's value proposition beyond open source",
      dealSignal: false,
      storyId: "mock-story-14",
    },
    {
      title: "Weaviate Expands Cloud Infrastructure to Support 10M+ Vector Dimensions",
      url: "https://example.com/weaviate-scale",
      source: "Weaviate Blog",
      publishedAt: T(5),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/weaviate.io",
      beat: "AI Infrastructure",
      category: "Product",
      companyTags: ["Weaviate"],
      summary: "Weaviate announced infrastructure improvements supporting vector databases with up to 10 million dimensions for large-scale semantic search applications.",
      bdRelevance: "Higher-dimensional vector support enables more sophisticated semantic search use cases. Watch for enterprise adoption.",
      relevanceScore: 6,
      impactScore: 5,
      impactReason: "Technical capability expansion addresses enterprise semantic search needs",
      dealSignal: false,
      storyId: "mock-story-15",
    },
    {
      title: "Pinecone Releases Vector Database Optimization for Real-time Inference",
      url: "https://example.com/pinecone-optimization",
      source: "VectorDB News",
      publishedAt: T(6),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/pinecone.io",
      beat: "AI Infrastructure",
      category: "Product",
      companyTags: ["Pinecone"],
      summary: "Pinecone released new optimization techniques for vector database queries, reducing latency by 40% in production environments.",
      bdRelevance: "Performance improvement in vector search enables new use cases for retrieval-augmented generation systems.",
      relevanceScore: 7,
      impactScore: 6,
      impactReason: "Incremental improvement in a foundational technology; enables better real-time experiences",
      dealSignal: false,
      storyId: "mock-story-16",
    },
    {
      title: "Weights & Biases Raises $49M Series D for ML Infrastructure Platform",
      url: "https://example.com/wandb-seriesd",
      source: "VentureBeat",
      publishedAt: T(7),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/wandb.com",
      beat: "AI Infrastructure",
      category: "Funding",
      companyTags: ["Weights & Biases"],
      summary: "Weights & Biases raised $49M in Series D funding to expand its experiment tracking and model monitoring platform used by leading ML teams.",
      bdRelevance: "Strong funding validates market need for ML observability. Potential integration opportunities with model deployment platforms.",
      relevanceScore: 7,
      impactScore: 6,
      impactReason: "Well-funded infrastructure company; establishes observability as key category",
      dealSignal: false,
      storyId: "mock-story-17",
    },
    {
      title: "Ray AI Infrastructure Platform Adds Native GPU Sharing for Cost Optimization",
      url: "https://example.com/ray-gpu-sharing",
      source: "Ray Blog",
      publishedAt: T(8),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/anyscale.com",
      beat: "AI Infrastructure",
      category: "Product",
      companyTags: ["Anyscale"],
      summary: "Anyscale released GPU sharing capabilities in Ray allowing multiple workloads to share single GPUs, reducing infrastructure costs by up to 50%.",
      bdRelevance: "Cost optimization in GPU infrastructure addresses key pain point for AI applications. Watch for adoption.",
      relevanceScore: 6,
      impactScore: 6,
      impactReason: "Cost optimization enables broader AI adoption; valuable for price-sensitive deployments",
      dealSignal: false,
      storyId: "mock-story-18",
    },
    {
      title: "Exa Launches AI Infrastructure Marketplace for Model Hosting and Inference",
      url: "https://example.com/exa-marketplace",
      source: "Exa Announcements",
      publishedAt: T(9),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/exa.ai",
      beat: "AI Infrastructure",
      category: "Product",
      companyTags: ["Exa"],
      summary: "Exa announced a marketplace connecting model developers with infrastructure providers for seamless model hosting and inference scaling.",
      bdRelevance: "Marketplace model could enable network effects in AI infrastructure. Watch for ecosystem development.",
      relevanceScore: 6,
      impactScore: 5,
      impactReason: "Marketplace approach to infrastructure distribution; potential ecosystem standard",
      dealSignal: false,
      storyId: "mock-story-19",
    },
    {
      title: "Modal Introduces Distributed Training Framework for LLMs",
      url: "https://example.com/modal-training",
      source: "Modal Blog",
      publishedAt: T(10),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/modal.com",
      beat: "AI Infrastructure",
      category: "Product",
      companyTags: ["Modal"],
      summary: "Modal released a distributed training framework enabling teams to train large language models across multiple GPUs with simplified infrastructure management.",
      bdRelevance: "Infrastructure for LLM training reduces deployment complexity. Watch for adoption among model-building teams.",
      relevanceScore: 8,
      impactScore: 7,
      impactReason: "Simplifies distributed training infrastructure; critical for scaling model development",
      dealSignal: false,
      storyId: "mock-story-20",
    },

    // ========== AI LABS (10 articles) ==========
    // dealSignal articles first, sorted newest → oldest
    {
      title: "Google DeepMind Achieves Breakthrough in AlphaFold 3 Protein Structure Prediction",
      url: "https://example.com/alphafold3",
      source: "Nature",
      publishedAt: T(1),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/deepmind.google",
      beat: "AI Labs",
      category: "AI/Models",
      companyTags: ["Google DeepMind"],
      summary: "Google DeepMind published AlphaFold 3 research enabling more accurate prediction of protein structures and interactions. Open-source release available.",
      bdRelevance: "Scientific AI breakthrough opens drug discovery and biotech applications. Watch for commercial applications from biotech startups.",
      relevanceScore: 8,
      impactScore: 9,
      impactReason: "Scientific breakthrough with broad commercial applications; enables new biotech ventures",
      dealSignal: true,
      dealSignalType: "product_launch",
      storyId: "mock-story-21",
    },
    {
      title: "xAI Releases Grok 2.0 with Advanced Reasoning Capabilities",
      url: "https://example.com/xai-grok20",
      source: "xAI Blog",
      publishedAt: T(2),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/x.ai",
      beat: "AI Labs",
      category: "AI/Models",
      companyTags: ["xAI"],
      summary: "xAI released Grok 2.0, showing significant improvements in mathematical reasoning and code generation compared to the original version. Available via API and on X platform.",
      bdRelevance: "Foundation model with strong reasoning capabilities. Watch for enterprise adoption and API integration patterns.",
      relevanceScore: 9,
      impactScore: 9,
      impactReason: "Advanced reasoning capabilities in frontier model; signals capability parity with leading labs",
      dealSignal: true,
      dealSignalType: "positioning_shift",
      storyId: "mock-story-22",
    },
    {
      title: "Anthropic and Google Announce Strategic Partnership on AI Safety Research",
      url: "https://example.com/anthropic-google",
      source: "Anthropic Blog",
      publishedAt: T(3),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/anthropic.com",
      beat: "AI Labs",
      category: "Partnerships",
      companyTags: ["Anthropic", "Google"],
      summary: "Anthropic and Google announced a joint research partnership focused on AI safety and interpretability. The collaboration will combine Anthropic's research with Google's infrastructure.",
      bdRelevance: "Major research partnership signals competitive positioning. Companies building on Claude may want to understand safety research direction and standards.",
      relevanceScore: 8,
      impactScore: 8,
      impactReason: "Major AI labs converging on safety research; may establish new industry standards",
      dealSignal: true,
      dealSignalType: "partnership_announced",
      storyId: "mock-story-23",
    },
    {
      title: "Meta Releases Llama 3.5 with 405B Parameter Model",
      url: "https://example.com/meta-llama35",
      source: "Meta Blog",
      publishedAt: T(4),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/meta.com",
      beat: "AI Labs",
      category: "AI/Models",
      companyTags: ["Meta"],
      summary: "Meta released Llama 3.5 including a 405B parameter model matching closed-source model performance. Available for commercial use.",
      bdRelevance: "Open source frontier model enables cost-effective enterprise deployments. Watch for adoption by model optimization startups.",
      relevanceScore: 7,
      impactScore: 8,
      impactReason: "Open source frontier model enables competitive alternatives to proprietary services",
      dealSignal: true,
      dealSignalType: "product_launch",
      storyId: "mock-story-24",
    },
    // non-dealSignal articles, sorted newest → oldest
    {
      title: "Mistral AI Releases 8x7B Mixture of Experts Model with Faster Inference",
      url: "https://example.com/mistral-moe",
      source: "Hugging Face",
      publishedAt: T(5),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/mistral.ai",
      beat: "AI Labs",
      category: "AI/Models",
      companyTags: ["Mistral"],
      summary: "Mistral released a Mixture of Experts variant of its 8x7B model achieving 2x faster inference while maintaining competitive reasoning performance.",
      bdRelevance: "Open source model improvements enable cost-effective alternatives to closed API services. Watch for enterprise adoption.",
      relevanceScore: 7,
      impactScore: 6,
      impactReason: "Open source model efficiency improvements; enables cost-conscious enterprise deployments",
      dealSignal: false,
      storyId: "mock-story-25",
    },
    {
      title: "OpenAI Releases GPT-4.5 with Improved Reasoning Capabilities",
      url: "https://example.com/openai-gpt45",
      source: "OpenAI Blog",
      publishedAt: T(6),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/openai.com",
      beat: "AI Labs",
      category: "AI/Models",
      companyTags: ["OpenAI"],
      summary: "OpenAI released GPT-4.5 with enhanced multi-step reasoning and improved code generation. The model shows 15% improvement in complex reasoning benchmarks.",
      bdRelevance: "Model capability progression affects competitive landscape for AI products. Assess impact on feature differentiation and performance requirements.",
      relevanceScore: 7,
      impactScore: 7,
      impactReason: "Incremental capability improvement in foundational model; raises bar for AI applications",
      dealSignal: false,
      storyId: "mock-story-26",
    },
    {
      title: "xAI Releases Grok-2 with Advanced Multimodal Understanding",
      url: "https://example.com/xai-grok2",
      source: "xAI Blog",
      publishedAt: T(7),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/x.ai",
      beat: "AI Labs",
      category: "AI/Models",
      companyTags: ["xAI"],
      summary: "xAI announced Grok-2 with advanced multimodal understanding including image, video, and document analysis. Model will be available on X platform.",
      bdRelevance: "Multimodal capabilities expanding across AI labs. Watch for integration opportunities in document processing and analysis applications.",
      relevanceScore: 6,
      impactScore: 6,
      impactReason: "Multimodal capabilities becoming standard; enables new application categories",
      dealSignal: false,
      storyId: "mock-story-27",
    },
    {
      title: "Cohere Launches Command R+ Model for Enterprise Applications",
      url: "https://example.com/cohere-commandr",
      source: "Cohere Blog",
      publishedAt: T(8),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/cohere.ai",
      beat: "AI Labs",
      category: "AI/Models",
      companyTags: ["Cohere"],
      summary: "Cohere released Command R+, an optimized model for enterprise RAG applications with improved reliability and reduced hallucination.",
      bdRelevance: "Enterprise-optimized models signal market focus on reliability. Watch for adoption in mission-critical applications.",
      relevanceScore: 6,
      impactScore: 6,
      impactReason: "Enterprise-focused model design addresses reliability concerns in production deployments",
      dealSignal: false,
      storyId: "mock-story-28",
    },
    {
      title: "Stability AI Releases Stable Image 3 with Higher Fidelity Image Generation",
      url: "https://example.com/stability-image3",
      source: "Stability AI Blog",
      publishedAt: T(9),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/stability.ai",
      beat: "AI Labs",
      category: "AI/Models",
      companyTags: ["Stability AI"],
      summary: "Stability AI released Stable Image 3 with improved quality and faster generation speeds for commercial image generation applications.",
      bdRelevance: "Improved image generation quality enables new creative and enterprise applications. Watch for adoption in design tools.",
      relevanceScore: 6,
      impactScore: 5,
      impactReason: "Image generation capability improvements expand use cases in design and creative workflows",
      dealSignal: false,
      storyId: "mock-story-29",
    },
    {
      title: "Anthropic Publishes Constitutional AI Research at ACL Conference",
      url: "https://example.com/anthropic-acl",
      source: "Anthropic Research",
      publishedAt: T(10),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/anthropic.com",
      beat: "AI Labs",
      category: "AI/Models",
      companyTags: ["Anthropic"],
      summary: "Anthropic published research on Constitutional AI improvements showing better alignment with human values at scale without human feedback.",
      bdRelevance: "Alignment research progress signals industry maturation toward safer AI systems. Watch for adoption of Constitutional AI techniques.",
      relevanceScore: 7,
      impactScore: 7,
      impactReason: "Alignment research progress moves toward safer production AI systems; may establish standards",
      dealSignal: false,
      storyId: "mock-story-30",
    },

    // ========== VERTICAL AI (10 articles) ==========
    // dealSignal articles first, sorted newest → oldest
    {
      title: "Sierra Completes $45M Series B for Enterprise Sales AI",
      url: "https://example.com/sierra-seriesb",
      source: "TechCrunch",
      publishedAt: T(1),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/sierrallm.com",
      beat: "Vertical AI",
      category: "Funding",
      companyTags: ["Sierra"],
      summary: "Sierra closed a $45M Series B to expand its enterprise sales AI platform. The round was led by Salesforce Ventures and existing investors.",
      bdRelevance: "Strong funding signals investor confidence in enterprise sales AI. Watch for Salesforce integration opportunities.",
      relevanceScore: 8,
      impactScore: 7,
      impactReason: "Well-funded vertical AI company; Salesforce backing suggests integration potential",
      dealSignal: true,
      dealSignalType: "funding_round",
      storyId: "mock-story-31",
    },
    {
      title: "Writer Raises $200M Series C for Enterprise Generative AI",
      url: "https://example.com/writer-seriec",
      source: "VentureBeat",
      publishedAt: T(2),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/writer.com",
      beat: "Vertical AI",
      category: "Funding",
      companyTags: ["Writer"],
      summary: "Writer closed a $200M Series C round at a $3.5B valuation to expand its enterprise AI platform for content generation and marketing.",
      bdRelevance: "Massive funding validates market for enterprise content generation AI. Watch for acquisition or IPO signals.",
      relevanceScore: 8,
      impactScore: 7,
      impactReason: "Well-funded vertical AI company signals strong market demand for enterprise generation",
      dealSignal: true,
      dealSignalType: "funding_round",
      storyId: "mock-story-32",
    },
    {
      title: "Glean Announces Integration with Microsoft Copilot for Enterprise Search",
      url: "https://example.com/glean-copilot",
      source: "Glean Blog",
      publishedAt: T(3),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/glean.com",
      beat: "Vertical AI",
      category: "Partnerships",
      companyTags: ["Glean"],
      summary: "Glean announced a partnership with Microsoft to integrate with Copilot, enabling AI-powered enterprise search across Microsoft 365 applications.",
      bdRelevance: "Microsoft partnership provides distribution channel for Glean. Watch for broader enterprise search market consolidation.",
      relevanceScore: 7,
      impactScore: 7,
      impactReason: "Strategic partnership with major platform; accelerates enterprise adoption of AI search",
      dealSignal: true,
      dealSignalType: "partnership_announced",
      storyId: "mock-story-33",
    },
    {
      title: "Moveworks Secures $300M Funding for Enterprise IT Automation",
      url: "https://example.com/moveworks-funding",
      source: "VentureBeat",
      publishedAt: T(4),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/moveworks.com",
      beat: "Vertical AI",
      category: "Funding",
      companyTags: ["Moveworks"],
      summary: "Moveworks raised $300M in funding at an $8B valuation to expand its AI platform for enterprise IT service automation and employee support.",
      bdRelevance: "Billion-dollar vertical AI company signals strong unit economics in IT automation. Watch for potential acquisition or IPO.",
      relevanceScore: 8,
      impactScore: 8,
      impactReason: "Billion-dollar vertical AI validates strong market for IT process automation",
      dealSignal: true,
      dealSignalType: "funding_round",
      storyId: "mock-story-34",
    },
    {
      title: "Harvey AI Lands Goldman Sachs as Major Enterprise Customer",
      url: "https://example.com/harvey-goldman",
      source: "VentureBeat",
      publishedAt: T(5),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/harvey.ai",
      beat: "Vertical AI",
      category: "Partnerships",
      companyTags: ["Harvey"],
      summary: "Harvey AI, the legal AI platform, announced Goldman Sachs as a major enterprise customer. Goldman will deploy Harvey across legal and compliance functions.",
      bdRelevance: "Tier-1 financial services adoption validates enterprise AI deployment model. Watch for Harvey's potential integration partnerships and ecosystem plays.",
      relevanceScore: 9,
      impactScore: 8,
      impactReason: "Validates enterprise AI adoption in highly regulated industries; opens market opportunities",
      dealSignal: true,
      dealSignalType: "customer_win",
      storyId: "mock-story-35",
    },
    // non-dealSignal articles, sorted newest → oldest
    {
      title: "Decagon Releases AI for Insurance Claims Processing",
      url: "https://example.com/decagon-claims",
      source: "TechCrunch",
      publishedAt: T(6),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/decagon.ai",
      beat: "Vertical AI",
      category: "Product",
      companyTags: ["Decagon"],
      summary: "Decagon launched an AI platform specifically designed for insurance claims processing, reducing processing time by 70% and improving accuracy.",
      bdRelevance: "Specialized insurance AI solution addresses critical industry process. Watch for insurance customer wins and partnerships.",
      relevanceScore: 6,
      impactScore: 6,
      impactReason: "Specialized vertical AI solution for high-value insurance process; demonstrates ROI focus",
      dealSignal: false,
      storyId: "mock-story-36",
    },
    {
      title: "Cognigy Announces AI Contact Center Solution with Sentiment Analysis",
      url: "https://example.com/cognigy-contact",
      source: "Cognigy Blog",
      publishedAt: T(7),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/cognigy.com",
      beat: "Vertical AI",
      category: "Product",
      companyTags: ["Cognigy"],
      summary: "Cognigy released an AI contact center solution with real-time sentiment analysis enabling better customer service routing and escalation decisions.",
      bdRelevance: "Customer service AI addressing key enterprise need. Watch for adoption by major contact center operators.",
      relevanceScore: 6,
      impactScore: 6,
      impactReason: "AI solution for large contact center market; addressable market of $100B+",
      dealSignal: false,
      storyId: "mock-story-37",
    },
    {
      title: "Rogo Expands Platform to Support Additional Enterprise Workflows",
      url: "https://example.com/rogo-expansion",
      source: "Rogo Blog",
      publishedAt: T(8),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/rogolegal.com",
      beat: "Vertical AI",
      category: "Product",
      companyTags: ["Rogo"],
      summary: "Rogo, the enterprise workflow automation platform, expanded to support supply chain management and procurement workflows. Integration with major ERP systems now available.",
      bdRelevance: "Supply chain AI is emerging as a key enterprise need. Rogo's expansion signals market development and potential partnership opportunities.",
      relevanceScore: 6,
      impactScore: 5,
      impactReason: "Addresses emerging enterprise need in supply chain optimization; expands addressable market",
      dealSignal: false,
      storyId: "mock-story-38",
    },
    {
      title: "Synthesia Launches AI Video Generation for Enterprise Communications",
      url: "https://example.com/synthesia-video",
      source: "Synthesia Blog",
      publishedAt: T(9),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/synthesia.io",
      beat: "Vertical AI",
      category: "Product",
      companyTags: ["Synthesia"],
      summary: "Synthesia released an AI video generation platform allowing enterprises to create personalized marketing and training videos at scale without actors.",
      bdRelevance: "AI video content creation enables new marketing and training workflows. Watch for enterprise adoption and integrations.",
      relevanceScore: 6,
      impactScore: 5,
      impactReason: "Vertical AI enabling new content creation workflows; expanding addressable market",
      dealSignal: false,
      storyId: "mock-story-39",
    },
    {
      title: "Levity AI Partners with Klaviyo for E-commerce Automation",
      url: "https://example.com/levity-klaviyo",
      source: "Levity Blog",
      publishedAt: T(10),
      ogImage: null,
      companyLogoUrl: "https://logo.clearbit.com/levity.ai",
      beat: "Vertical AI",
      category: "Partnerships",
      companyTags: ["Levity AI", "Klaviyo"],
      summary: "Levity AI announced a partnership with Klaviyo to enable AI-powered automation in e-commerce workflows including order processing and customer support.",
      bdRelevance: "E-commerce platform partnership signals vertical AI expansion into retail. Watch for ecosystem growth.",
      relevanceScore: 6,
      impactScore: 5,
      impactReason: "E-commerce platform partnership enables scaled distribution of vertical AI",
      dealSignal: false,
      storyId: "mock-story-40",
    },
  ],
};
