import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";
import { fetchRoboticsNews } from "@/lib/exa";
import { generateDigest, type DigestArticle } from "@/lib/summarize";

const CATEGORY_COLORS: Record<string, string> = {
  Funding: "#10b981",
  Product: "#3b82f6",
  "AI/Models": "#8b5cf6",
  Partnerships: "#f59e0b",
  Hiring: "#ec4899",
  General: "#6b7280",
};

function buildEmailHtml(digest: {
  executiveSummary: string;
  articles: DigestArticle[];
  generatedAt: string;
}): string {
  const date = new Date(digest.generatedAt).toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const articleRows = digest.articles
    .map((a) => {
      const color = CATEGORY_COLORS[a.category] ?? "#6b7280";
      const companies =
        a.companyTags.length > 0
          ? `<span style="color:#94a3b8;font-size:12px;">${a.companyTags.join(" · ")}</span>`
          : "";
      return `
      <div style="border:1px solid #1e293b;border-radius:8px;padding:16px;margin-bottom:12px;background:#0f172a;">
        <div style="display:flex;align-items:center;gap:8px;margin-bottom:8px;">
          <span style="background:${color}22;color:${color};font-size:11px;font-weight:600;padding:2px 8px;border-radius:4px;border:1px solid ${color}44;">${a.category}</span>
          ${companies}
          <span style="color:#475569;font-size:11px;margin-left:auto;">${a.source}</span>
        </div>
        <a href="${a.url}" style="color:#e2e8f0;font-size:15px;font-weight:600;text-decoration:none;">${a.title}</a>
        <p style="color:#94a3b8;font-size:13px;margin:8px 0 4px;">${a.summary}</p>
        <p style="color:#64748b;font-size:12px;margin:0;border-left:2px solid #f59e0b;padding-left:8px;">BD: ${a.bdRelevance}</p>
      </div>`;
    })
    .join("");

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="background:#020817;margin:0;padding:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <div style="max-width:680px;margin:0 auto;padding:32px 16px;">
    <div style="text-align:center;margin-bottom:32px;">
      <h1 style="color:#f1f5f9;font-size:24px;font-weight:700;margin:0;">Physical AI Daily</h1>
      <p style="color:#64748b;font-size:13px;margin:4px 0 0;">${date}</p>
    </div>
    <div style="background:#0f172a;border:1px solid #1e293b;border-left:3px solid #3b82f6;border-radius:8px;padding:20px;margin-bottom:24px;">
      <h2 style="color:#93c5fd;font-size:13px;font-weight:600;text-transform:uppercase;letter-spacing:0.05em;margin:0 0 10px;">Today's Big Picture</h2>
      <p style="color:#cbd5e1;font-size:14px;line-height:1.6;margin:0;">${digest.executiveSummary}</p>
    </div>
    <h2 style="color:#64748b;font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:0.1em;margin:0 0 12px;">${digest.articles.length} Stories</h2>
    ${articleRows}
    <p style="color:#334155;font-size:11px;text-align:center;margin-top:24px;">Physical AI Daily · Generated by Claude + Exa</p>
  </div>
</body>
</html>`;
}

export async function POST(req: NextRequest) {
  const authHeader = req.headers.get("authorization");
  const expectedSecret = process.env.CRON_SECRET;

  if (!expectedSecret || authHeader !== `Bearer ${expectedSecret}`) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const articles = await fetchRoboticsNews();
    if (articles.length === 0) {
      return NextResponse.json({ error: "No articles found" }, { status: 404 });
    }

    const digest = await generateDigest(articles);
    const html = buildEmailHtml(digest);

    const resend = new Resend(process.env.RESEND_API_KEY!);
    const date = new Date().toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
    });

    const { data, error } = await resend.emails.send({
      from: "Physical AI Daily <onboarding@resend.dev>",
      to: ["fokjenhong@gmail.com"],
      subject: `Physical AI Daily — ${date}`,
      html,
    });

    if (error) {
      console.error("Resend error:", error);
      return NextResponse.json({ error: "Email send failed" }, { status: 500 });
    }

    return NextResponse.json({ success: true, emailId: data?.id });
  } catch (err) {
    console.error("Send-digest error:", err);
    return NextResponse.json({ error: "Internal error" }, { status: 500 });
  }
}
